apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: flask-test
  name: flask-test
spec:
  replicas: 1
  selector:
    deploymentconfig: flask-test
  strategy:
    activeDeadlineSeconds: 21600
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: flask-test
        deploymentconfig: flask-test
    spec:
      containers:
        - image: 172.30.1.1:5000/myproject/flask-test
          imagePullPolicy: Always
          name: flask-test
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - flask-test
        from:
          kind: ImageStreamTag
          name: 'flask-test:latest'
          namespace: myproject
      type: ImageChange
    - type: ConfigChange
