/**
* Sample Jenkinsfile
* It shows hot to build a Docker image
 */
pipeline {
  agent {
    node {
      label 'python'
    }
  }
  options {
    timeout(time: 10, unit: 'MINUTES')
  }
  environment {
    templatePath = 'ssh://rmp-bot@gerrit.it.here.com:29418/olp/ingestion'
    templateName = 'flask-app'
  }
  stages {
    stage('Init') {
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject() {
              echo "Using project: ${openshift.project()}"
            }
          }
        }
        sh 'python --version'
        sh 'pip --version'
        sh 'rm -rf .git jenkins-agent flask-app'
      }
    }
    stage('SCM') {
      steps {
        git url: 'https://github.com/dav1dli/flask-ci-doc.git'
      }
    }
    stage('Test') {
      steps {
        dir ('flask-app') {
          sh '''
            pip install -r requirements.txt --user
            python run.py &
            nosetests . --with-xunit
          '''
          junit "nosetests.xml"
        }
      }
    }
    stage('NewBuild') {
      when {
        expression {
          openshift.withCluster() {
            openshift.withProject() {
              return !openshift.selector("bc", "${templateName}").exists();
            }
          }
        }
      }
      steps{
        echo "Build Docker image"
        dir ('flask-app') {
          script {
            openshift.withCluster() {
              openshift.withProject() {
                openshift.newBuild("--name=${templateName}", "--strategy docker", "--docker-image=myproject/python", "--binary=true")
              }
            }
          }
        }
      }
    }
  }
}
