apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-test
  name: flask-test
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: flask-test
  sessionAffinity: None
  type: ClusterIP
