FROM registry.redhat.io/openshift3/jenkins-slave-base-rhel7
LABEL com.redhat.component="jenkins-agent-python-rhel7-container" \
      name="openshift3/jenkins-agent-python-rhel7" \
      version="3.6" \
      architecture="x86_64" \
      io.k8s.display-name="Jenkins Agent Python" \
      io.k8s.description="The jenkins build agent Python" \
      io.openshift.tags="openshift,jenkins,agent,python,python3,builder"

ENV PYTHON_VERSION=3.6 \
    PATH=$HOME/.local/bin/:$PATH

RUN yum-config-manager --enable rhel-server-rhscl-7-rpms && \
    yum-config-manager --enable rhel-server-rhscl-7-rpms && \
    INSTALL_PKGS="rh-python36-python-devel rh-python36-python-pip rh-python36-python-setuptools httpd httpd-devel" && \
    yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    rpm -e --nodeps redhat-logos && \
    yum clean all -y && \
    rm -rf /var/cache/yum

RUN chown -R 1001:0 $HOME && \
    chmod -R g+rw $HOME

USER 1001
