FROM openshift/jenkins-slave-base-centos7
LABEL com.redhat.component="jenkins-agent-python-centos7-container" \
      name="openshift/jenkins-agent-python-centos7" \
      version="2.7" \
      architecture="x86_64" \
      io.k8s.display-name="Jenkins Agent Python" \
      io.k8s.description="The jenkins build agent Python" \
      io.openshift.tags="openshift,jenkins,agent,python,builder"

ENV PYTHON_VERSION=2.7 \
    PATH=$HOME/.local/bin/:$PATH

RUN INSTALL_PKGS="python-devel python-setuptools python27-python-pip httpd httpd-devel" && \
    yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    yum clean all -y && \
    rm -rf /var/cache/yum

RUN chown -R 1001:0 $HOME && \
    chmod -R g+rw $HOME

USER 1001
